name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.10.1"
          channel: stable
      - run: echo $FIREBASE_CONFIG | base64 -d > lib/firebase_options.dart
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      - run: flutter pub get
      - run: flutter build web --release --no-tree-shake-icons 
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_GRADIENT_GENERATOR }}'
          projectId: flutter-gradient-generator
